/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "RooRatio.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(RooRatio);

 RooRatio::RooRatio(const char *name, const char *title,
                        RooAbsReal& _numerator,
                        RooAbsReal& _denominator) :
   RooAbsReal(name,title),
   numerator("numerator","numerator",this,_numerator),
   denominator("denominator","denominator",this,_denominator)
 {
 }


 RooRatio::RooRatio(const RooRatio& other, const char* name) :
   RooAbsReal(other,name),
   numerator("numerator",this,other.numerator),
   denominator("denominator",this,other.denominator)
 {
 }



 Double_t RooRatio::evaluate() const
 {
   return denominator ? numerator/denominator : 0.0 ;
 }



